name: submarine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cryptography: ^2.7.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  nostr: ^1.5.0
  system_theme: ^3.1.0
  toastification: ^2.2.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_512_circle.png