name: submarine
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  intl: any
  ndk: ^0.5.0
  nip01: ^0.3.0+1
  nip19: ^0.2.0
  nostr_widgets: ^0.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  sembast_cache_manager: ^1.0.2
  sembast_web: ^2.4.2
  system_theme: ^3.1.2
  toastification: ^3.0.3
  url_launcher: ^6.3.1
  window_manager: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
