name: submarine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  drift: ^2.20.2
  drift_flutter: ^0.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: any
  nostr: ^1.5.0
  pointycastle: ^3.9.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.3
  build_runner: ^2.4.12

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo_512_circle.png