name: nostr_passwords
description: Reference Dart implementation of a password manager protocol built on Nostr.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.4
resolution: workspace

dependencies:
  crypto: ^3.0.7
  ndk: ^0.10.1
  sync_engine_shim_for_ndk: ^0.8.0
  unorm_dart: ^0.3.2

dev_dependencies:
  bip340: ^0.3.1
  lints: ^6.0.0
  sembast: ^3.8.11
  test: ^1.25.6
