import 'cli_exception.dart';

const _bwOnlyTemplates = {
  'folder',
  'collection',
  'item-collections',
  'org-collection',
  'send.file',
  'send.text',
};

/// What `bw get template <object>` prints, keys in bw's order. As in bw, there
/// is no template for an SSH key.
Object template(String object) => switch (object.toLowerCase()) {
  'item' => {
    'type': 1,
    'name': 'Item name',
    'favorite': false,
    'reprompt': 0,
    'notes': 'Some notes about this item.',
    'fields': <Object>[],
    'passwordHistory': <Object>[],
  },
  'item.field' => {'type': 0, 'name': 'Field name', 'value': 'Some value'},
  'item.login' => {
    'uris': <Object>[],
    'username': 'jdoe',
    'password': 'myp@ssword123',
    'totp': 'JBSWY3DPEHPK3PXP',
    'fido2Credentials': <Object>[],
  },
  'item.login.uri' => {'uri': 'https://google.com'},
  'item.card' => {
    'cardholderName': 'John Doe',
    'brand': 'visa',
    'number': '4242424242424242',
    'expMonth': '04',
    'expYear': '2023',
    'code': '123',
  },
  'item.identity' => {
    'title': 'Mr',
    'firstName': 'John',
    'middleName': 'William',
    'lastName': 'Doe',
    'address1': '123 Any St',
    'address2': 'Apt #123',
    'city': 'New York',
    'state': 'NY',
    'postalCode': '10001',
    'country': 'US',
    'company': 'Acme Inc.',
    'email': 'john@company.com',
    'phone': '5555551234',
    'ssn': '000-123-4567',
    'username': 'jdoe',
    'passportNumber': 'US-123456789',
    'licenseNumber': 'D123-12-123-12333',
  },
  'item.securenote' => {'type': 0},
  'item.bankaccount' => {
    'bankName': 'Acme Bank',
    'nameOnAccount': 'John Doe',
    'accountType': 'checking',
    'accountNumber': '000123456789',
    'routingNumber': '000000000',
    'branchNumber': '000',
    'pin': '1234',
    'swiftCode': 'ACMEUS33',
    'iban': 'GB00ACME12345600000001',
    'bankContactPhone': '1-800-123-4567',
  },
  'item.driverslicense' => {
    'firstName': 'Jane',
    'middleName': 'A.',
    'lastName': 'Smith',
    'dateOfBirth': '1990-01-15',
    'licenseNumber': 'D12345678',
    'issuingCountry': 'US',
    'issuingState': 'CA',
    'issueDate': '2020-06-01',
    'expirationDate': '2028-06-01',
    'issuingAuthority': 'California DMV',
    'licenseClass': 'C',
  },
  'item.passport' => {
    'surname': 'Smith',
    'givenName': 'Jane',
    'dateOfBirth': '1990-01-15',
    'sex': 'F',
    'birthPlace': 'Los Angeles, CA',
    'nationality': 'USA',
    'issuingCountry': 'US',
    'passportNumber': 'A12345678',
    'passportType': 'P',
    'nationalIdentificationNumber': '123-45-6789',
    'issuingAuthority': 'U.S. Department of State',
    'issueDate': '2020-06-01',
    'expirationDate': '2030-06-01',
  },
  final object when _bwOnlyTemplates.contains(object) => throw CliException(
    'Submarine does not support `get template $object`.',
  ),
  _ => throw CliException('Unknown template object.'),
};
