/// The 500 names most given to girls and the 500 most given to boys born in
/// the US from 1966 to 2008, per the Social Security Administration (public
/// domain), the names given to both counted once.
final englishFirstNames = _split(_firstNames);

/// The 1000 most common surnames of the 2010 US Census (public domain),
/// written as usual: the Census spells them in capitals, without spaces or
/// apostrophes.
final englishLastNames = _split(_lastNames);

List<String> _split(String names) => names.trim().split(RegExp(r',\s*'));

const _firstNames = '''
Aaliyah, Aaron, Abby, Abel, Abigail, Abraham, Adam, Addison, Adrian, Adriana,
Adrianna, Adrienne, Aidan, Aiden, Aimee, Alan, Alana, Albert, Alberto, Alec,
Alejandra, Alejandro, Alex, Alexa, Alexander, Alexandra, Alexandria, Alexia,
Alexis, Alfonso, Alfred, Alfredo, Alice, Alicia, Alisa, Alisha, Alison, Alissa,
Allan, Allen, Allison, Allyson, Alondra, Alvin, Alyssa, Amanda, Amber, Amelia,
Amy, Ana, Anastasia, Andre, Andrea, Andres, Andrew, Andy, Angel, Angela,
Angelica, Angelina, Angelo, Angie, Anita, Ann, Anna, Anne, Annette, Annie,
Anthony, Antoine, Antoinette, Antonio, April, Ariana, Arianna, Ariel, Armando,
Arthur, Arturo, Ashlee, Ashleigh, Ashley, Ashlyn, Ashton, Asia, Aubrey, Audrey,
Austin, Autumn, Ava, Avery, Ayden, Bailey, Barbara, Barry, Beau, Becky, Belinda,
Ben, Benjamin, Bernard, Beth, Bethany, Betty, Beverly, Bianca, Billy, Blake,
Bobbie, Bobby, Bonnie, Brad, Braden, Bradley, Brady, Branden, Brandi, Brandon,
Brandy, Braxton, Brayden, Breanna, Brenda, Brendan, Brenden, Brennan, Brent,
Bret, Brett, Brian, Briana, Brianna, Bridget, Britney, Brittany, Brittney,
Brock, Brody, Brooke, Brooklyn, Bruce, Bryan, Bryant, Bryce, Bryson, Byron,
Cade, Caden, Caitlin, Caitlyn, Caleb, Callie, Calvin, Cameron, Camille, Candace,
Candice, Cara, Carissa, Carl, Carla, Carlos, Carly, Carmen, Carol, Carolina,
Caroline, Carolyn, Carrie, Carson, Carter, Casey, Cassandra, Cassidy, Cassie,
Catherine, Cathy, Cecilia, Cedric, Celeste, Cesar, Chad, Chance, Chandler,
Charity, Charlene, Charles, Charlie, Charlotte, Chase, Chelsea, Chelsey, Cheryl,
Cheyenne, Chloe, Chris, Christa, Christian, Christie, Christina, Christine,
Christopher, Christy, Ciara, Cierra, Cindy, Claire, Clara, Clarence, Clarissa,
Claudia, Clay, Clayton, Clifford, Clifton, Clint, Clinton, Cody, Colby, Cole,
Colin, Colleen, Collin, Colton, Conner, Connie, Connor, Cooper, Corbin, Corey,
Cory, Courtney, Craig, Cristian, Cristina, Crystal, Curtis, Cynthia, Daisy,
Dakota, Dale, Dallas, Dalton, Damian, Damien, Damon, Dana, Dane, Daniel,
Daniela, Danielle, Danny, Dante, Darin, Darius, Darlene, Darnell, Darrell,
Darren, Darrin, Darryl, Daryl, David, Dawn, Dawson, Dean, Deandre, Deanna,
Debbie, Deborah, Debra, Delaney, Demetrius, Denise, Dennis, Derek, Derrick,
Desiree, Desmond, Destiny, Devin, Devon, Diamond, Diana, Diane, Diego, Dillon,
Dominic, Dominick, Dominique, Don, Donald, Donna, Donnie, Donovan, Dorothy,
Douglas, Drake, Drew, Duane, Dustin, Dwayne, Dwight, Dylan, Earl, Ebony, Eddie,
Edgar, Eduardo, Edward, Edwin, Eileen, Elaine, Elena, Eli, Elias, Elijah, Elisa,
Elisabeth, Elise, Elizabeth, Ella, Ellen, Elliot, Elliott, Emanuel, Emilio,
Emily, Emma, Emmanuel, Enrique, Eric, Erica, Erick, Erik, Erika, Erin, Ernest,
Ernesto, Esmeralda, Esteban, Esther, Ethan, Eugene, Eva, Evan, Evelyn, Fabian,
Faith, Felicia, Felipe, Felix, Fernando, Frances, Francis, Francisco, Frank,
Franklin, Fred, Frederick, Fredrick, Gabriel, Gabriela, Gabriella, Gabrielle,
Gage, Garrett, Gary, Gavin, Genesis, Geoffrey, George, Gerald, Gerardo, Gianna,
Gilbert, Gilberto, Gina, Giovanni, Giselle, Glen, Glenn, Gloria, Gordon, Grace,
Gracie, Graham, Grant, Grayson, Greg, Gregory, Gretchen, Griffin, Guadalupe,
Guillermo, Gustavo, Guy, Gwendolyn, Hailey, Haley, Hanna, Hannah, Harold,
Harrison, Harry, Hayden, Hayley, Heath, Heather, Hector, Heidi, Helen, Henry,
Herbert, Hillary, Holly, Hope, Howard, Hugo, Hunter, Ian, Irene, Iris, Isaac,
Isabel, Isabella, Isabelle, Isaiah, Ismael, Israel, Ivan, Jace, Jack, Jackie,
Jackson, Jaclyn, Jacob, Jacqueline, Jacquelyn, Jada, Jade, Jaden, Jaime, Jake,
Jakob, Jalen, Jamal, James, Jamie, Jana, Jane, Janelle, Janet, Janice, Jared,
Jarrett, Jarrod, Jasmin, Jasmine, Jason, Javier, Jay, Jayden, Jaylen, Jayson,
Jazmin, Jazmine, Jean, Jeanette, Jeff, Jeffery, Jeffrey, Jenna, Jennifer, Jenny,
Jeremiah, Jeremy, Jermaine, Jerome, Jerry, Jesse, Jessica, Jessie, Jesus, Jill,
Jillian, Jim, Jimmy, Joann, Joanna, Joanne, Jocelyn, Jodi, Jody, Joe, Joel,
Joey, Johanna, John, Johnathan, Johnathon, Johnny, Jon, Jonah, Jonathan,
Jonathon, Jordan, Jordyn, Jorge, Jose, Joseph, Josephine, Joshua, Josiah, Josue,
Joy, Joyce, Juan, Juanita, Judith, Judy, Julia, Julian, Juliana, Julianna,
Julie, Julio, Julius, Justin, Justine, Kaden, Kaitlin, Kaitlyn, Kaleb, Kameron,
Kara, Karen, Kari, Karina, Karl, Karla, Kasey, Kassandra, Kate, Katelyn,
Katelynn, Katherine, Kathleen, Kathryn, Kathy, Katie, Katrina, Kayla, Kaylee,
Keegan, Keith, Kelley, Kelli, Kellie, Kelly, Kelsey, Kelvin, Kendall, Kendra,
Kendrick, Kennedy, Kenneth, Kenny, Kent, Keri, Kerri, Kerry, Kevin, Kiara, Kim,
Kimberley, Kimberly, Kira, Kirk, Kirsten, Kody, Krista, Kristen, Kristi,
Kristie, Kristin, Kristina, Kristine, Kristopher, Kristy, Krystal, Kurt, Kyla,
Kyle, Kylee, Kyler, Kylie, Kyra, Lacey, Lamar, Lance, Landon, Lane, Larry,
Latasha, Latoya, Laura, Lauren, Laurie, Lawrence, Layla, Leah, Lee, Leigh, Leo,
Leon, Leonard, Leonardo, Leroy, Lesley, Leslie, Leticia, Levi, Lewis, Liam,
Liliana, Lillian, Lily, Linda, Lindsay, Lindsey, Lisa, Lloyd, Logan, Lonnie,
Lorena, Lorenzo, Lori, Louis, Lucas, Lucy, Luis, Lukas, Luke, Lydia, Lynn,
Mackenzie, Madeline, Madelyn, Madison, Maggie, Makayla, Malachi, Malcolm, Malik,
Mallory, Mandy, Manuel, Marc, Marco, Marcos, Marcus, Margaret, Maria, Mariah,
Mariana, Marie, Marilyn, Marina, Mario, Marisa, Marisol, Marissa, Mark, Marlene,
Marlon, Marquis, Marshall, Martha, Martin, Marvin, Mary, Mason, Mathew, Matthew,
Maureen, Maurice, Max, Maxwell, Maya, Mayra, Mckenna, Mckenzie, Meagan, Megan,
Meghan, Melanie, Melinda, Melissa, Melody, Melvin, Mercedes, Meredith, Mia,
Micah, Michael, Michaela, Micheal, Michele, Michelle, Miguel, Mikayla, Mike,
Miles, Mindy, Miranda, Miriam, Misty, Mitchell, Moises, Molly, Monica, Monique,
Morgan, Mya, Myles, Nadia, Nancy, Naomi, Natalia, Natalie, Natasha, Nathan,
Nathaniel, Neal, Neil, Nelson, Nevaeh, Nicholas, Nichole, Nickolas, Nicolas,
Nicole, Nikki, Nina, Noah, Noel, Nolan, Nora, Norma, Norman, Oliver, Olivia,
Omar, Orlando, Oscar, Owen, Pablo, Paige, Pamela, Parker, Patricia, Patrick,
Paul, Paula, Payton, Pedro, Peggy, Penny, Perry, Peter, Peyton, Philip, Phillip,
Preston, Priscilla, Quentin, Quinn, Quinton, Rachael, Rachel, Rachelle, Rafael,
Ralph, Ramon, Randall, Randy, Raquel, Raul, Raven, Ray, Raymond, Rebecca,
Rebekah, Regina, Reginald, Rene, Renee, Rhonda, Ricardo, Richard, Rick, Ricky,
Riley, Rita, Robert, Roberto, Robin, Robyn, Rochelle, Roderick, Rodney, Rodolfo,
Roger, Roland, Roman, Ronald, Ronnie, Rosa, Rose, Ross, Roxanne, Roy, Ruben,
Ruby, Rudy, Russell, Ruth, Ryan, Sabrina, Sadie, Sally, Salvador, Sam, Samantha,
Samuel, Sandra, Sandy, Santiago, Sara, Sarah, Sasha, Saul, Savannah, Scott,
Sean, Sebastian, Selena, Serena, Sergio, Seth, Shana, Shane, Shanna, Shannon,
Sharon, Shaun, Shauna, Shawn, Shawna, Shayla, Sheila, Shelby, Shelley, Shelly,
Sheri, Sherri, Sherry, Shirley, Sierra, Simon, Skylar, Skyler, Sofia, Sonia,
Sonya, Sophia, Sophie, Spencer, Stacey, Stacie, Stacy, Stanley, Stefanie,
Stephanie, Stephen, Steve, Steven, Stuart, Summer, Susan, Suzanne, Sydney,
Sylvia, Tabitha, Tamara, Tammy, Tania, Tanner, Tanya, Tara, Tasha, Tatiana,
Taylor, Teresa, Terrance, Terrell, Terrence, Terri, Terry, Tessa, Theodore,
Theresa, Thomas, Tia, Tiffany, Timothy, Tina, Toby, Todd, Tommy, Toni, Tony,
Tonya, Tori, Tracey, Traci, Tracie, Tracy, Travis, Trent, Trenton, Trevor, Trey,
Tricia, Trinity, Trisha, Tristan, Troy, Tucker, Ty, Tyler, Tyrone, Tyson,
Valeria, Valerie, Vanessa, Vernon, Veronica, Vicki, Victor, Victoria, Vincent,
Virginia, Vivian, Wade, Walter, Wanda, Warren, Wayne, Wendy, Wesley, Whitney,
William, Willie, Wyatt, Xavier, Yesenia, Yolanda, Yvette, Yvonne, Zachariah,
Zachary, Zachery, Zackary, Zane, Zoe
''';

const _lastNames = '''
Abbott, Acevedo, Acosta, Adams, Adkins, Aguilar, Aguirre, Ahmed, Alexander,
Alfaro, Ali, Allen, Allison, Alvarado, Alvarez, Andersen, Anderson, Andrade,
Andrews, Anthony, Archer, Arellano, Arias, Armstrong, Arnold, Arroyo, Ashley,
Atkins, Atkinson, Austin, Avalos, Avery, Avila, Ayala, Ayers, Bailey, Baker,
Baldwin, Ball, Ballard, Banks, Barajas, Barber, Barker, Barnes, Barnett, Barr,
Barrera, Barrett, Barron, Barry, Bartlett, Barton, Bass, Bates, Bauer, Bautista,
Baxter, Bean, Beard, Beasley, Beck, Becker, Beil, Bell, Beltran, Bender,
Benitez, Benjamin, Bennett, Benson, Bentley, Benton, Berg, Berger, Bernal,
Bernard, Berry, Best, Bishop, Black, Blackburn, Blackwell, Blair, Blake,
Blanchard, Blankenship, Blevins, Bond, Bonilla, Booker, Boone, Booth, Bowen,
Bowers, Bowman, Boyd, Boyer, Boyle, Bradford, Bradley, Bradshaw, Brady, Branch,
Brandt, Bravo, Brennan, Brewer, Bridges, Briggs, Brock, Brooks, Brown, Browning,
Bruce, Bryan, Bryant, Buchanan, Buck, Buckley, Bullock, Burch, Burgess, Burke,
Burnett, Burns, Burton, Bush, Butler, Byrd, Cabrera, Cain, Calderon, Caldwell,
Calhoun, Callahan, Camacho, Cameron, Campbell, Campos, Cannon, Cano, Cantrell,
Cantu, Cardenas, Carey, Carlson, Carpenter, Carr, Carrillo, Carroll, Carson,
Carter, Case, Casey, Castaneda, Castillo, Castro, Cervantes, Chambers, Chan,
Chandler, Chang, Chapman, Charles, Chase, Chavez, Chen, Cherry, Choi,
Christensen, Christian, Chung, Church, Cisneros, Clark, Clarke, Clay, Clayton,
Clements, Cline, Cobb, Cochran, Coffey, Cohen, Cole, Coleman, Collier, Collins,
Colon, Combs, Compton, Conley, Conner, Conrad, Contreras, Conway, Cook, Cooper,
Copeland, Cordova, Corona, Correa, Cortes, Cortez, Costa, Cox, Craig, Crane,
Crawford, Crosby, Cross, Cruz, Cuevas, Cummings, Cunningham, Curry, Curtis,
Dalton, Daniel, Daniels, Daugherty, Davenport, David, Davidson, Davila, Davis,
Dawson, Day, De Jesus, De La Cruz, De La Rosa, De Leon, Dean, Decker, Delgado,
Dennis, Diaz, Dickerson, Dickson, Dillon, Dixon, Dodson, Dominguez, Donaldson,
Donovan, Dorsey, Dougherty, Douglas, Doyle, Drake, Duarte, Dudley, Duffy, Duke,
Duncan, Dunlap, Dunn, Duran, Durham, Dyer, Eaton, Edwards, Elliott, Ellis,
Ellison, English, Enriquez, Erickson, Escobar, Esparza, Espinosa, Espinoza,
Esquivel, Estes, Estrada, Evans, Everett, Farley, Farmer, Farrell, Faulkner,
Felix, Ferguson, Fernandez, Fields, Figueroa, Finley, Fischer, Fisher,
Fitzgerald, Fitzpatrick, Fleming, Fletcher, Flores, Flowers, Floyd, Flynn,
Foley, Ford, Foster, Fowler, Fox, Francis, Franco, Frank, Franklin, Frazier,
Frederick, Freeman, French, Friedman, Frost, Fry, Frye, Fuentes, Fuller, Gaines,
Galindo, Gallagher, Gallegos, Galvan, Garcia, Gardner, Garner, Garrett,
Garrison, Garza, Gates, Gentry, George, Gibbs, Gibson, Gilbert, Giles, Gill,
Gillespie, Gilmore, Glass, Glenn, Glover, Golden, Gomez, Gonzales, Gonzalez,
Good, Goodman, Goodwin, Gordon, Gould, Graham, Grant, Graves, Gray, Green,
Greene, Greer, Gregory, Griffin, Griffith, Grimes, Gross, Guerra, Guerrero,
Guevara, Gutierrez, Guzman, Hahn, Hail, Hale, Haley, Hall, Hamilton, Hammond,
Hampton, Hancock, Hanna, Hansen, Hanson, Hardin, Harding, Hardy, Harmon, Harper,
Harrell, Harrington, Harris, Harrison, Hart, Hartman, Harvey, Hawkins, Hayden,
Hayes, Haynes, Heath, Hebert, Henderson, Hendricks, Hendrix, Henry, Hensley,
Henson, Herman, Hernandez, Herrera, Herring, Hess, Hester, Hickman, Hicks,
Higgins, Hill, Hines, Hinton, Ho, Hobbs, Hodge, Hodges, Hoffman, Hogan, Holland,
Holloway, Holmes, Holt, Hood, Hoover, Hopkins, Horn, Horne, Horton, House,
Houston, Howard, Howe, Howell, Huang, Hubbard, Huber, Hudson, Huerta, Huff,
Huffman, Hughes, Hull, Humphrey, Hunt, Hunter, Hurley, Hurst, Hutchinson, Huynh,
Ibarra, Ingram, Jackson, Jacobs, Jacobson, James, Jaramillo, Jarvis, Jefferson,
Jenkins, Jennings, Jensen, Jimenez, Johns, Johnson, Johnston, Jones, Jordan,
Joseph, Juarez, Kane, Kaur, Keith, Keller, Kelley, Kelly, Kemp, Kennedy, Kent,
Kerr, Khan, Kim, King, Kirby, Kirk, Klein, Kline, Knapp, Knight, Knox, Koch,
Kramer, Krueger, Lam, Lamb, Lambert, Landry, Lane, Lang, Lara, Larsen, Larson,
Lawrence, Lawson, Le, LeBlanc, Leach, Leal, Lee, Leon, Leonard, Lester, Levy,
Lewis, Li, Lim, Lin, Lindsey, Little, Liu, Livingston, Lloyd, Logan, Long,
Lopez, Love, Lowe, Lowery, Lozano, Lu, Lucas, Lucero, Lugo, Luna, Lynch, Lynn,
Lyons, MacDonald, Macias, Mack, Madden, Maddox, Magana, Mahoney, Maldonado,
Malone, Mann, Manning, Marin, Marks, Marquez, Marsh, Marshall, Martin, Martinez,
Mason, Massey, Mata, Mathews, Mathis, Matthews, Maxwell, May, Mayer, Maynard,
Mayo, Mays, McBride, McCall, McCann, McCarthy, McCarty, McClain, McClure,
McConnell, McCormick, McCoy, McCullough, McDaniel, McDonald, McDowell,
McFarland, McGee, McGuire, McIntosh, McIntyre, McKay, McKee, McKenzie, McKinney,
McLaughlin, McLean, McMahon, McMillan, McPherson, Meadows, Medina, Medrano,
Mejia, Melendez, Melton, Mendez, Mendoza, Mercado, Merritt, Meyer, Meyers, Meza,
Michael, Middleton, Miles, Miller, Mills, Miranda, Mitchell, Molina, Monroe,
Montes, Montgomery, Montoya, Moody, Moon, Moore, Mora, Morales, Moran, Moreno,
Morgan, Morris, Morrison, Morrow, Morse, Morton, Moses, Mosley, Moss, Moyer,
Mueller, Mullen, Mullins, Munoz, Murillo, Murphy, Murray, Myers, Nash, Nava,
Navarro, Neal, Nelson, Newman, Newton, Nguyen, Nichols, Nicholson, Nielsen,
Nixon, Noble, Nolan, Norman, Norris, Norton, Novak, Nunez, O'Brien, O'Connell,
O'Connor, O'Donnell, O'Neal, O'Neill, Ochoa, Odom, Oliver, Olsen, Olson, Orozco,
Orr, Ortega, Ortiz, Osborne, Owen, Owens, Pace, Pacheco, Padilla, Page,
Palacios, Palmer, Park, Parker, Parks, Parra, Parrish, Parsons, Patel, Patrick,
Patterson, Patton, Paul, Payne, Pearson, Peck, Pena, Pennington, Peralta, Perez,
Perkins, Perry, Person, Peters, Petersen, Peterson, Pham, Phan, Phelps,
Phillips, Pierce, Pineda, Pittman, Pitts, Pollard, Ponce, Poole, Pope, Porter,
Portillo, Potter, Potts, Powell, Powers, Pratt, Preston, Price, Prince, Proctor,
Pruitt, Pugh, Quinn, Quintana, Quintero, Ramirez, Ramos, Ramsey, Randall,
Randolph, Rangel, Rasmussen, Ray, Raymond, Reed, Reese, Reeves, Reid, Reilly,
Reyes, Reyna, Reynolds, Rhodes, Rice, Rich, Richard, Richards, Richardson,
Richmond, Riley, Rios, Rivas, Rivera, Rivers, Roach, Robbins, Roberson, Roberts,
Robertson, Robinson, Robles, Rocha, Rodgers, Rodriguez, Rogers, Rojas, Rollins,
Roman, Romero, Rosales, Rosario, Rosas, Rose, Ross, Roth, Rowe, Rowland, Roy,
Rubio, Ruiz, Rush, Russell, Russo, Ryan, Salas, Salazar, Salgado, Salinas,
Sampson, Sanchez, Sanders, Sandoval, Sanford, Santana, Santiago, Santos,
Saunders, Savage, Sawyer, Schaefer, Schmidt, Schmitt, Schneider, Schroeder,
Schultz, Schwartz, Scott, Sellers, Serrano, Sexton, Shaffer, Shah, Shannon,
Sharp, Shaw, Shelton, Shepard, Shepherd, Sheppard, Sherman, Shields, Short,
Sierra, Silva, Simmons, Simon, Simpson, Sims, Singh, Singleton, Skinner, Sloan,
Small, Smith, Snow, Snyder, Solis, Solomon, Sosa, Soto, Sparks, Spears, Spence,
Spencer, Stafford, Stanley, Stanton, Stark, Steele, Stein, Stephens, Stephenson,
Stevens, Stevenson, Stewart, Stokes, Stone, Stout, Strickland, Strong, Stuart,
Suarez, Sullivan, Summers, Sutton, Swanson, Sweeney, Tang, Tanner, Tapia, Tate,
Taylor, Terrell, Terry, Thomas, Thompson, Thornton, Todd, Torres, Townsend,
Tran, Travis, Trejo, Trevino, Trujillo, Truong, Tucker, Turner, Tyler,
Underwood, Valdez, Valencia, Valentine, Valenzuela, Vance, Vang, Vargas,
Vasquez, Vaughan, Vaughn, Vazquez, Vega, Velasquez, Velazquez, Velez, Ventura,
Villa, Villalobos, Villanueva, Villarreal, Villegas, Vincent, Vo, Vu, Wade,
Wagner, Walker, Wall, Wallace, Waller, Walls, Walsh, Walter, Walters, Walton,
Wang, Ward, Ware, Warner, Warren, Washington, Waters, Watkins, Watson, Watts,
Weaver, Webb, Weber, Webster, Weeks, Weiss, Welch, Wells, West, Wheeler,
Whitaker, White, Whitehead, Whitney, Wiggins, Wilcox, Wiley, Wilkerson, Wilkins,
Wilkinson, Williams, Williamson, Willis, Wilson, Winters, Wise, Wolf, Wolfe,
Wong, Wood, Woodard, Woods, Woodward, Wright, Wu, Wyatt, Xiong, Yang, Yates,
Yoder, York, Young, Yu, Zamora, Zavala, Zhang, Zimmerman, Zuniga
''';
